### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by pudelos** [FranMaric/Messenger-Bubble-UI#1]
Hi!
Overwriting other applications does not work. How can I fix it?

**Comment by FranMaric** [comment]
Greetings,

This version only supports bubble inside the app not outside to overwrite
other apps which is only available on android.

Fram Marić

**Comment by pudelos** [comment]
oh too bad. I have a big problem because I need to make a communication application in Flutter with a speech bubble which overwrites other applications. Unfortunately, I can't find anything on the internet about this. Could you give me a hint or a link? 

Witek Milewski

**Comment by FranMaric** [comment]
https://pub.dev/packages/bubble_overlay

You could use this package.

čet, 15. tra 2021. u 14:29 pudelek.pl ***@***.***> napisao je:
